# 这里说明，此config的大部分设置已迁移至setting.py，请到setting.py做相应修改

setting:
  request: # 网络请求设置
    timeout: 10 # gitee友链配置
    ssl: false  # gitee友链配置

  gitee_friends_links: # gitee友链配置
    enable: true
    type: normal # volantis用户请在这里填写 volantis
    owner: ccknbc # 填写你的gitee用户名
    repo: blogroll # 填写你的gitee仓库名
    state: open # 填写抓取的issue状态(open/progressing/closed)
    labelid: none # none关闭功能

  github_friends_links: # github友链配置
    enable: true
    type: normal # volantis用户请在这里填写 volantis
    owner: ccknbc-actions # 填写你的github用户名
    repo: blogroll # 填写你的github仓库名
    state: open # 填写抓取的issue状态(open/closed)
    label: none # none关闭功能