name: "Keep Workflow Alive"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout codes"
        uses: actions/checkout@main

      - name: "Keep Workflow Alive"
        run: |
          date > KeepWorkflowAlive.txt
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Keep Workflow Alive"
          git push
